language: node_js
node_js:
  - '10'
services:
  - docker

before_install:
  - npm install
  - npm install -g parcel-bundler

# script:
#   - parcel build ./server.js
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#   - docker build -t kylvia/docker_demo:latest .
#   - docker push kylvia/docker_demo:latest
